import type { Metadata } from "next";
import localFont from "next/font/local";
import { Red_Hat_Display } from "next/font/google";
import "./globals.css";
import LenisSmoothScroll from "@/components/Lenis";

// Google Font — Red Hat Display
const redHatDisplay = Red_Hat_Display({
  subsets: ["latin"],
  variable: "--font-red-hat",
  display: "swap",
});

// Local Serif Font — IvyMode
const ivyMode = localFont({
  src: "./fonts/IvyMode-Regular.woff2",
  variable: "--font-ivy",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        suppressHydrationWarning
        className={`
          ${redHatDisplay.variable}
          ${ivyMode.variable}
          antialiased
        `}
      >
        <LenisSmoothScroll />
        {children}
      </body>
    </html>
  );
}
